In [4]:
import json
import os

In [5]:
files = os.listdir("../data/raw")

print("Number of files:", len(files))
print("First file:", files[0])

Number of files: 1244
First file: 1082591.json

In [6]:
file_path = "../data/raw/" + files[0]

with open(file_path, "r") as f:
    match = json.load(f)

print(type(match))

<class 'dict'>

In [7]:
print(match.keys())

dict_keys(['meta', 'info', 'innings'])

In [8]:
print(match["info"].keys())

dict_keys(['balls_per_over', 'city', 'dates', 'event', 'gender', 'match_type', 'officials', 'outcome', 'overs', 'player_of_match', 'players', 'registry', 'season', 'team_type', 'teams', 'toss', 'venue'])

In [9]:
print(match["info"]["teams"])

['Sunrisers Hyderabad', 'Royal Challengers Bangalore']

In [10]:
print(match["info"]["players"])

{'Royal Challengers Bangalore': ['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM Jadhav', 'SR Watson', 'Sachin Baby', 'STR Binny', 'S Aravind', 'TS Mills', 'YS Chahal', 'A Choudhary'], 'Sunrisers Hyderabad': ['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuvraj Singh', 'DJ Hooda', 'BCJ Cutting', 'NV Ojha', 'Bipul Sharma', 'B Kumar', 'A Nehra', 'Rashid Khan']}

In [11]:
print(match["info"]["toss"])

{'decision': 'field', 'winner': 'Royal Challengers Bangalore'}

In [12]:
print(match["info"]["outcome"])

{'by': {'runs': 35}, 'winner': 'Sunrisers Hyderabad'}

In [13]:
print(type(match["innings"]))

<class 'list'>

In [14]:
print(len(match["innings"]))

2

In [15]:
print(match["innings"][0].keys())

dict_keys(['team', 'overs', 'powerplays'])

In [16]:
print(match["innings"][0]["team"])

Sunrisers Hyderabad

In [17]:
print(match["innings"][1]["team"])

Royal Challengers Bangalore

In [18]:
print(type(match["innings"][0]["overs"]))

<class 'list'>

In [19]:
print(len(match["innings"][0]["overs"]))

20

In [20]:
print(match["innings"][0]["overs"][0])

{'over': 0, 'deliveries': [{'actual_delivery': '0.1', 'batter': 'DA Warner', 'bowler': 'TS Mills', 'non_striker': 'S Dhawan', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'actual_delivery': '0.2', 'batter': 'DA Warner', 'bowler': 'TS Mills', 'non_striker': 'S Dhawan', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'actual_delivery': '0.3', 'batter': 'DA Warner', 'bowler': 'TS Mills', 'non_striker': 'S Dhawan', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'actual_delivery': '0.4', 'batter': 'DA Warner', 'bowler': 'TS Mills', 'non_striker': 'S Dhawan', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'actual_delivery': '0.5', 'batter': 'DA Warner', 'bowler': 'TS Mills', 'extras': {'wides': 2}, 'non_striker': 'S Dhawan', 'runs': {'batter': 0, 'extras': 2, 'total': 2}}, {'actual_delivery': '0.5', 'batter': 'S Dhawan', 'bowler': 'TS Mills', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'actual_delivery': '0.6', 'batter': 'S Dhawan', 'bowler': 'TS Mills', 'extras': {'legbyes': 1}, 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}]}

In [21]:
for innings in match["innings"]:
    for over in innings["overs"]:
        for delivery in over["deliveries"]:
            if "wickets" in delivery:
                print(delivery)
                break

{'actual_delivery': '1.4', 'batter': 'DA Warner', 'bowler': 'A Choudhary', 'non_striker': 'S Dhawan', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'DA Warner', 'fielders': [{'name': 'Mandeep Singh'}]}]}
{'actual_delivery': '10.3', 'batter': 'S Dhawan', 'bowler': 'STR Binny', 'non_striker': 'MC Henriques', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'S Dhawan', 'fielders': [{'name': 'Sachin Baby'}]}]}
{'actual_delivery': '15.2', 'batter': 'MC Henriques', 'bowler': 'YS Chahal', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'MC Henriques', 'fielders': [{'name': 'Sachin Baby'}]}]}
{'actual_delivery': '18.4', 'batter': 'Yuvraj Singh', 'bowler': 'TS Mills', 'non_striker': 'DJ Hooda', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'bowled', 'player_out': 'Yuvraj Singh'}]}
{'actual_delivery': '5.4', 'batter': 'Mandeep Singh', 'bowler': 'Rashid Khan', 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'bowled', 'player_out': 'Mandeep Singh'}]}
{'actual_delivery': '6.3', 'batter': 'CH Gayle', 'bowler': 'DJ Hooda', 'non_striker': 'TM Head', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'CH Gayle', 'fielders': [{'name': 'DA Warner'}]}]}
{'actual_delivery': '11.4', 'batter': 'KM Jadhav', 'bowler': 'MC Henriques', 'non_striker': 'TM Head', 'runs': {'batter': 1, 'extras': 0, 'total': 1}, 'wickets': [{'kind': 'run out', 'player_out': 'KM Jadhav', 'fielders': [{'name': 'BCJ Cutting'}]}]}
{'actual_delivery': '12.5', 'batter': 'TM Head', 'bowler': 'Rashid Khan', 'non_striker': 'SR Watson', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'TM Head', 'fielders': [{'name': 'Yuvraj Singh'}]}]}
{'actual_delivery': '13.4', 'batter': 'Sachin Baby', 'bowler': 'Bipul Sharma', 'non_striker': 'SR Watson', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'Sachin Baby', 'fielders': [{'name': 'MC Henriques'}]}]}
{'actual_delivery': '16.5', 'batter': 'STR Binny', 'bowler': 'B Kumar', 'non_striker': 'SR Watson', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'STR Binny', 'fielders': [{'name': 'Yuvraj Singh'}]}]}
{'actual_delivery': '17.3', 'batter': 'SR Watson', 'bowler': 'A Nehra', 'non_striker': 'S Aravind', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'SR Watson', 'fielders': [{'name': 'MC Henriques'}]}]}
{'actual_delivery': '18.5', 'batter': 'TS Mills', 'bowler': 'B Kumar', 'non_striker': 'YS Chahal', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'TS Mills', 'fielders': [{'name': 'DA Warner'}]}]}
{'actual_delivery': '19.4', 'batter': 'A Choudhary', 'bowler': 'BCJ Cutting', 'non_striker': 'YS Chahal', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'run out', 'player_out': 'YS Chahal', 'fielders': [{'name': 'CJ Jordan', 'substitute': True}]}]}

In [22]:
print(match["info"]["players"])

{'Royal Challengers Bangalore': ['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM Jadhav', 'SR Watson', 'Sachin Baby', 'STR Binny', 'S Aravind', 'TS Mills', 'YS Chahal', 'A Choudhary'], 'Sunrisers Hyderabad': ['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuvraj Singh', 'DJ Hooda', 'BCJ Cutting', 'NV Ojha', 'Bipul Sharma', 'B Kumar', 'A Nehra', 'Rashid Khan']}

In [23]:
import pandas as pd

match_data = {
    "team_1": match["info"]["teams"][0],
    "team_2": match["info"]["teams"][1],
    "venue": match["info"]["venue"],
    "toss_winner": match["info"]["toss"]["winner"],
    "toss_decision": match["info"]["toss"]["decision"],
    "winner": match["info"]["outcome"]["winner"]
}

df = pd.DataFrame([match_data])

df

ModuleNotFoundError: No module named 'pandas'

In [24]:
import sys

print(sys.executable)

c:\Users\SAI PAVAN KARTHIK\OneDrive\Desktop\Versus\venv\Scripts\python.exe

In [25]:
import pandas as pd

print(pd.__version__)

3.0.5

In [26]:
match_data = {
    "team_1": match["info"]["teams"][0],
    "team_2": match["info"]["teams"][1],
    "venue": match["info"]["venue"],
    "toss_winner": match["info"]["toss"]["winner"],
    "toss_decision": match["info"]["toss"]["decision"],
    "winner": match["info"]["outcome"]["winner"]
}

df = pd.DataFrame([match_data])

df

,team_1,team_2,venue,toss_winner,toss_decision,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,field,Sunrisers Hyderabad

In [27]:
id="j4x3rk"
innings = match["innings"][0]

print(innings["team"])
print(len(innings["overs"]))

Sunrisers Hyderabad
20

In [28]:
id="m3x9qa"
total_deliveries = 0

for over in innings["overs"]:
    total_deliveries += len(over["deliveries"])

print("Total deliveries:", total_deliveries)

Total deliveries: 125

In [29]:
id="p6d1wh"
for over in innings["overs"]:
    for delivery in over["deliveries"]:
        print(
            delivery["actual_delivery"],
            delivery["batter"],
            delivery["bowler"],
            delivery["runs"]
        )

0.1 DA Warner TS Mills {'batter': 0, 'extras': 0, 'total': 0}
0.2 DA Warner TS Mills {'batter': 0, 'extras': 0, 'total': 0}
0.3 DA Warner TS Mills {'batter': 4, 'extras': 0, 'total': 4}
0.4 DA Warner TS Mills {'batter': 0, 'extras': 0, 'total': 0}
0.5 DA Warner TS Mills {'batter': 0, 'extras': 2, 'total': 2}
0.5 S Dhawan TS Mills {'batter': 0, 'extras': 0, 'total': 0}
0.6 S Dhawan TS Mills {'batter': 0, 'extras': 1, 'total': 1}
1.1 S Dhawan A Choudhary {'batter': 1, 'extras': 0, 'total': 1}
1.2 DA Warner A Choudhary {'batter': 4, 'extras': 0, 'total': 4}
1.3 DA Warner A Choudhary {'batter': 0, 'extras': 1, 'total': 1}
1.3 DA Warner A Choudhary {'batter': 6, 'extras': 0, 'total': 6}
1.4 DA Warner A Choudhary {'batter': 0, 'extras': 0, 'total': 0}
1.5 MC Henriques A Choudhary {'batter': 0, 'extras': 0, 'total': 0}
1.6 MC Henriques A Choudhary {'batter': 4, 'extras': 0, 'total': 4}
2.1 S Dhawan TS Mills {'batter': 1, 'extras': 0, 'total': 1}
2.2 MC Henriques TS Mills {'batter': 0, 'extras': 0, 'total': 0}
2.3 MC Henriques TS Mills {'batter': 0, 'extras': 0, 'total': 0}
2.4 MC Henriques TS Mills {'batter': 3, 'extras': 0, 'total': 3}
2.5 S Dhawan TS Mills {'batter': 1, 'extras': 0, 'total': 1}
2.6 MC Henriques TS Mills {'batter': 1, 'extras': 0, 'total': 1}
3.1 MC Henriques YS Chahal {'batter': 0, 'extras': 0, 'total': 0}
3.2 MC Henriques YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
3.3 S Dhawan YS Chahal {'batter': 0, 'extras': 0, 'total': 0}
3.4 S Dhawan YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
3.5 MC Henriques YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
3.6 S Dhawan YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
4.1 S Dhawan S Aravind {'batter': 1, 'extras': 0, 'total': 1}
4.2 MC Henriques S Aravind {'batter': 1, 'extras': 0, 'total': 1}
4.3 S Dhawan S Aravind {'batter': 1, 'extras': 0, 'total': 1}
4.4 MC Henriques S Aravind {'batter': 2, 'extras': 0, 'total': 2}
4.5 MC Henriques S Aravind {'batter': 4, 'extras': 0, 'total': 4}
4.6 MC Henriques S Aravind {'batter': 0, 'extras': 0, 'total': 0}
5.1 S Dhawan SR Watson {'batter': 4, 'extras': 0, 'total': 4}
5.2 S Dhawan SR Watson {'batter': 4, 'extras': 0, 'total': 4}
5.3 S Dhawan SR Watson {'batter': 0, 'extras': 0, 'total': 0}
5.4 S Dhawan SR Watson {'batter': 4, 'extras': 0, 'total': 4}
5.5 S Dhawan SR Watson {'batter': 4, 'extras': 0, 'total': 4}
5.6 S Dhawan SR Watson {'batter': 1, 'extras': 0, 'total': 1}
6.1 S Dhawan YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
6.2 MC Henriques YS Chahal {'batter': 0, 'extras': 0, 'total': 0}
6.3 MC Henriques YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
6.4 S Dhawan YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
6.5 MC Henriques YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
6.6 S Dhawan YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
7.1 S Dhawan TM Head {'batter': 1, 'extras': 0, 'total': 1}
7.2 MC Henriques TM Head {'batter': 1, 'extras': 0, 'total': 1}
7.3 S Dhawan TM Head {'batter': 1, 'extras': 0, 'total': 1}
7.4 MC Henriques TM Head {'batter': 6, 'extras': 0, 'total': 6}
7.5 MC Henriques TM Head {'batter': 1, 'extras': 0, 'total': 1}
7.6 S Dhawan TM Head {'batter': 1, 'extras': 0, 'total': 1}
8.1 S Dhawan YS Chahal {'batter': 2, 'extras': 0, 'total': 2}
8.2 S Dhawan YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
8.3 MC Henriques YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
8.4 S Dhawan YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
8.5 MC Henriques YS Chahal {'batter': 2, 'extras': 0, 'total': 2}
8.6 MC Henriques YS Chahal {'batter': 2, 'extras': 0, 'total': 2}
9.1 S Dhawan A Choudhary {'batter': 0, 'extras': 0, 'total': 0}
9.2 S Dhawan A Choudhary {'batter': 1, 'extras': 0, 'total': 1}
9.3 MC Henriques A Choudhary {'batter': 1, 'extras': 0, 'total': 1}
9.4 S Dhawan A Choudhary {'batter': 1, 'extras': 0, 'total': 1}
9.5 MC Henriques A Choudhary {'batter': 1, 'extras': 0, 'total': 1}
9.6 S Dhawan A Choudhary {'batter': 0, 'extras': 0, 'total': 0}
10.1 MC Henriques STR Binny {'batter': 1, 'extras': 0, 'total': 1}
10.2 S Dhawan STR Binny {'batter': 4, 'extras': 0, 'total': 4}
10.3 S Dhawan STR Binny {'batter': 0, 'extras': 0, 'total': 0}
10.4 MC Henriques STR Binny {'batter': 1, 'extras': 0, 'total': 1}
10.5 Yuvraj Singh STR Binny {'batter': 2, 'extras': 0, 'total': 2}
10.6 Yuvraj Singh STR Binny {'batter': 2, 'extras': 0, 'total': 2}
11.1 MC Henriques S Aravind {'batter': 1, 'extras': 0, 'total': 1}
11.2 Yuvraj Singh S Aravind {'batter': 0, 'extras': 0, 'total': 0}
11.3 Yuvraj Singh S Aravind {'batter': 1, 'extras': 0, 'total': 1}
11.4 MC Henriques S Aravind {'batter': 1, 'extras': 0, 'total': 1}
11.5 Yuvraj Singh S Aravind {'batter': 4, 'extras': 0, 'total': 4}
11.6 Yuvraj Singh S Aravind {'batter': 1, 'extras': 0, 'total': 1}
12.1 Yuvraj Singh A Choudhary {'batter': 4, 'extras': 0, 'total': 4}
12.2 Yuvraj Singh A Choudhary {'batter': 6, 'extras': 0, 'total': 6}
12.3 Yuvraj Singh A Choudhary {'batter': 4, 'extras': 0, 'total': 4}
12.4 Yuvraj Singh A Choudhary {'batter': 0, 'extras': 0, 'total': 0}
12.5 Yuvraj Singh A Choudhary {'batter': 0, 'extras': 1, 'total': 1}
12.5 Yuvraj Singh A Choudhary {'batter': 2, 'extras': 0, 'total': 2}
12.6 Yuvraj Singh A Choudhary {'batter': 1, 'extras': 0, 'total': 1}
13.1 Yuvraj Singh SR Watson {'batter': 4, 'extras': 0, 'total': 4}
13.2 Yuvraj Singh SR Watson {'batter': 1, 'extras': 0, 'total': 1}
13.3 MC Henriques SR Watson {'batter': 1, 'extras': 0, 'total': 1}
13.4 Yuvraj Singh SR Watson {'batter': 1, 'extras': 0, 'total': 1}
13.5 MC Henriques SR Watson {'batter': 0, 'extras': 0, 'total': 0}
13.6 MC Henriques SR Watson {'batter': 1, 'extras': 0, 'total': 1}
14.1 MC Henriques S Aravind {'batter': 4, 'extras': 0, 'total': 4}
14.2 MC Henriques S Aravind {'batter': 1, 'extras': 0, 'total': 1}
14.3 Yuvraj Singh S Aravind {'batter': 6, 'extras': 0, 'total': 6}
14.4 Yuvraj Singh S Aravind {'batter': 1, 'extras': 0, 'total': 1}
14.5 MC Henriques S Aravind {'batter': 6, 'extras': 0, 'total': 6}
14.6 MC Henriques S Aravind {'batter': 1, 'extras': 0, 'total': 1}
15.1 MC Henriques YS Chahal {'batter': 0, 'extras': 0, 'total': 0}
15.2 MC Henriques YS Chahal {'batter': 0, 'extras': 0, 'total': 0}
15.3 Yuvraj Singh YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
15.4 DJ Hooda YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
15.5 Yuvraj Singh YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
15.6 DJ Hooda YS Chahal {'batter': 1, 'extras': 0, 'total': 1}
16.1 DJ Hooda TS Mills {'batter': 1, 'extras': 0, 'total': 1}
16.2 Yuvraj Singh TS Mills {'batter': 0, 'extras': 0, 'total': 0}
16.3 Yuvraj Singh TS Mills {'batter': 4, 'extras': 0, 'total': 4}
16.4 Yuvraj Singh TS Mills {'batter': 1, 'extras': 0, 'total': 1}
16.5 DJ Hooda TS Mills {'batter': 0, 'extras': 0, 'total': 0}
16.6 DJ Hooda TS Mills {'batter': 1, 'extras': 0, 'total': 1}
17.1 DJ Hooda A Choudhary {'batter': 6, 'extras': 0, 'total': 6}
17.2 DJ Hooda A Choudhary {'batter': 1, 'extras': 0, 'total': 1}
17.3 Yuvraj Singh A Choudhary {'batter': 0, 'extras': 1, 'total': 1}
17.3 Yuvraj Singh A Choudhary {'batter': 0, 'extras': 1, 'total': 1}
17.3 Yuvraj Singh A Choudhary {'batter': 4, 'extras': 0, 'total': 4}
17.4 Yuvraj Singh A Choudhary {'batter': 1, 'extras': 0, 'total': 1}
17.5 DJ Hooda A Choudhary {'batter': 2, 'extras': 0, 'total': 2}
17.6 DJ Hooda A Choudhary {'batter': 1, 'extras': 0, 'total': 1}
18.1 DJ Hooda TS Mills {'batter': 1, 'extras': 0, 'total': 1}
18.2 Yuvraj Singh TS Mills {'batter': 4, 'extras': 0, 'total': 4}
18.3 Yuvraj Singh TS Mills {'batter': 6, 'extras': 0, 'total': 6}
18.4 Yuvraj Singh TS Mills {'batter': 0, 'extras': 0, 'total': 0}
18.5 BCJ Cutting TS Mills {'batter': 1, 'extras': 0, 'total': 1}
18.6 DJ Hooda TS Mills {'batter': 0, 'extras': 0, 'total': 0}
19.1 BCJ Cutting SR Watson {'batter': 1, 'extras': 0, 'total': 1}
19.2 DJ Hooda SR Watson {'batter': 1, 'extras': 0, 'total': 1}
19.3 BCJ Cutting SR Watson {'batter': 6, 'extras': 0, 'total': 6}
19.4 BCJ Cutting SR Watson {'batter': 2, 'extras': 0, 'total': 2}
19.5 BCJ Cutting SR Watson {'batter': 0, 'extras': 0, 'total': 0}
19.6 BCJ Cutting SR Watson {'batter': 6, 'extras': 0, 'total': 6}

In [30]:
from collections import defaultdict

player_stats = defaultdict(lambda: {
    "runs": 0,
    "balls_faced": 0,
    "fours": 0,
    "sixes": 0,
    "runs_conceded": 0,
    "balls_bowled": 0,
    "wickets": 0,
    "dismissals": 0
})

In [31]:
for over in innings["overs"]:
    for delivery in over["deliveries"]:

        batter = delivery["batter"]
        bowler = delivery["bowler"]

        runs = delivery["runs"]

        # Batter runs
        player_stats[batter]["runs"] += runs["batter"]

        # Count 4s and 6s
        if runs["batter"] == 4:
            player_stats[batter]["fours"] += 1

        if runs["batter"] == 6:
            player_stats[batter]["sixes"] += 1

        # Batter faced a legal ball
        if "extras" not in delivery or (
            "wides" not in delivery["extras"]
            and "noballs" not in delivery["extras"]
        ):
            player_stats[batter]["balls_faced"] += 1

        # Bowler information
        player_stats[bowler]["runs_conceded"] += runs["total"]

        # Bowler faced a legal delivery
        if "extras" not in delivery or (
            "wides" not in delivery["extras"]
            and "noballs" not in delivery["extras"]
        ):
            player_stats[bowler]["balls_bowled"] += 1

        # Wickets
        if "wickets" in delivery:
            for wicket in delivery["wickets"]:

                player_out = wicket["player_out"]

                player_stats[player_out]["dismissals"] += 1

                # Bowler gets credit for most dismissals,
                # but NOT run out / retired hurt / obstructing the field
                if wicket["kind"] not in [
                    "run out",
                    "retired hurt",
                    "retired out",
                    "obstructing the field"
                ]:
                    player_stats[bowler]["wickets"] += 1

In [32]:
stats_df = pd.DataFrame.from_dict(
    player_stats,
    orient="index"
)

stats_df

,runs,balls_faced,fours,sixes,runs_conceded,balls_bowled,wickets,dismissals
DA Warner,14,7,2,1,0,0,0,1
TS Mills,0,0,0,0,32,24,1,0
S Dhawan,40,31,5,0,0,0,0,1
A Choudhary,0,0,0,0,55,24,1,0
MC Henriques,52,37,3,2,0,0,0,1
YS Chahal,0,0,0,0,22,24,1,0
S Aravind,0,0,0,0,36,18,0,0
SR Watson,0,0,0,0,41,18,0,0
TM Head,0,0,0,0,11,6,0,0
STR Binny,0,0,0,0,10,6,1,0
Yuvraj Singh,62,27,7,3,0,0,0,1
DJ Hooda,16,12,0,1,0,0,0,0
BCJ Cutting,16,6,0,2,0,0,0,0

In [33]:
stats_df["strike_rate"] = (
    stats_df["runs"] / stats_df["balls_faced"] * 100
).fillna(0)

stats_df["economy"] = (
    stats_df["runs_conceded"] / stats_df["balls_bowled"] * 6
).fillna(0)

stats_df

,runs,balls_faced,fours,sixes,runs_conceded,balls_bowled,wickets,dismissals,strike_rate,economy
DA Warner,14,7,2,1,0,0,0,1,200.000000,0.000000
TS Mills,0,0,0,0,32,24,1,0,0.000000,8.000000
S Dhawan,40,31,5,0,0,0,0,1,129.032258,0.000000
A Choudhary,0,0,0,0,55,24,1,0,0.000000,13.750000
MC Henriques,52,37,3,2,0,0,0,1,140.540541,0.000000
YS Chahal,0,0,0,0,22,24,1,0,0.000000,5.500000
S Aravind,0,0,0,0,36,18,0,0,0.000000,12.000000
SR Watson,0,0,0,0,41,18,0,0,0.000000,13.666667
TM Head,0,0,0,0,11,6,0,0,0.000000,11.000000
STR Binny,0,0,0,0,10,6,1,0,0.000000,10.000000
Yuvraj Singh,62,27,7,3,0,0,0,1,229.629630,0.000000
DJ Hooda,16,12,0,1,0,0,0,0,133.333333,0.000000
BCJ Cutting,16,6,0,2,0,0,0,0,266.666667,0.000000

In [35]:
def calculate_player_stats(innings):
    print("Processing:", innings["team"])

In [36]:
calculate_player_stats(match["innings"][0])

Processing: Sunrisers Hyderabad

In [37]:
from collections import defaultdict

def calculate_player_stats(innings):

    player_stats = defaultdict(lambda: {
        "runs": 0,
        "balls_faced": 0,
        "fours": 0,
        "sixes": 0,
        "runs_conceded": 0,
        "balls_bowled": 0,
        "wickets": 0,
        "dismissals": 0
    })

    print("Processing:", innings["team"])

In [38]:
calculate_player_stats(match["innings"][0])

Processing: Sunrisers Hyderabad

In [39]:
from collections import defaultdict

def calculate_player_stats(innings):

    player_stats = defaultdict(lambda: {
        "runs": 0,
        "balls_faced": 0,
        "fours": 0,
        "sixes": 0,
        "runs_conceded": 0,
        "balls_bowled": 0,
        "wickets": 0,
        "dismissals": 0
    })

    for over in innings["overs"]:
        for delivery in over["deliveries"]:

            batter = delivery["batter"]
            bowler = delivery["bowler"]

            runs = delivery["runs"]

            print(
                batter,
                "faced",
                bowler,
                "→",
                runs
            )

In [40]:
calculate_player_stats(match["innings"][0])

DA Warner faced TS Mills → {'batter': 0, 'extras': 0, 'total': 0}
DA Warner faced TS Mills → {'batter': 0, 'extras': 0, 'total': 0}
DA Warner faced TS Mills → {'batter': 4, 'extras': 0, 'total': 4}
DA Warner faced TS Mills → {'batter': 0, 'extras': 0, 'total': 0}
DA Warner faced TS Mills → {'batter': 0, 'extras': 2, 'total': 2}
S Dhawan faced TS Mills → {'batter': 0, 'extras': 0, 'total': 0}
S Dhawan faced TS Mills → {'batter': 0, 'extras': 1, 'total': 1}
S Dhawan faced A Choudhary → {'batter': 1, 'extras': 0, 'total': 1}
DA Warner faced A Choudhary → {'batter': 4, 'extras': 0, 'total': 4}
DA Warner faced A Choudhary → {'batter': 0, 'extras': 1, 'total': 1}
DA Warner faced A Choudhary → {'batter': 6, 'extras': 0, 'total': 6}
DA Warner faced A Choudhary → {'batter': 0, 'extras': 0, 'total': 0}
MC Henriques faced A Choudhary → {'batter': 0, 'extras': 0, 'total': 0}
MC Henriques faced A Choudhary → {'batter': 4, 'extras': 0, 'total': 4}
S Dhawan faced TS Mills → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced TS Mills → {'batter': 0, 'extras': 0, 'total': 0}
MC Henriques faced TS Mills → {'batter': 0, 'extras': 0, 'total': 0}
MC Henriques faced TS Mills → {'batter': 3, 'extras': 0, 'total': 3}
S Dhawan faced TS Mills → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced TS Mills → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced YS Chahal → {'batter': 0, 'extras': 0, 'total': 0}
MC Henriques faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced YS Chahal → {'batter': 0, 'extras': 0, 'total': 0}
S Dhawan faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced S Aravind → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced S Aravind → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced S Aravind → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced S Aravind → {'batter': 2, 'extras': 0, 'total': 2}
MC Henriques faced S Aravind → {'batter': 4, 'extras': 0, 'total': 4}
MC Henriques faced S Aravind → {'batter': 0, 'extras': 0, 'total': 0}
S Dhawan faced SR Watson → {'batter': 4, 'extras': 0, 'total': 4}
S Dhawan faced SR Watson → {'batter': 4, 'extras': 0, 'total': 4}
S Dhawan faced SR Watson → {'batter': 0, 'extras': 0, 'total': 0}
S Dhawan faced SR Watson → {'batter': 4, 'extras': 0, 'total': 4}
S Dhawan faced SR Watson → {'batter': 4, 'extras': 0, 'total': 4}
S Dhawan faced SR Watson → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced YS Chahal → {'batter': 0, 'extras': 0, 'total': 0}
MC Henriques faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced TM Head → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced TM Head → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced TM Head → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced TM Head → {'batter': 6, 'extras': 0, 'total': 6}
MC Henriques faced TM Head → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced TM Head → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced YS Chahal → {'batter': 2, 'extras': 0, 'total': 2}
S Dhawan faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced YS Chahal → {'batter': 2, 'extras': 0, 'total': 2}
MC Henriques faced YS Chahal → {'batter': 2, 'extras': 0, 'total': 2}
S Dhawan faced A Choudhary → {'batter': 0, 'extras': 0, 'total': 0}
S Dhawan faced A Choudhary → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced A Choudhary → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced A Choudhary → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced A Choudhary → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced A Choudhary → {'batter': 0, 'extras': 0, 'total': 0}
MC Henriques faced STR Binny → {'batter': 1, 'extras': 0, 'total': 1}
S Dhawan faced STR Binny → {'batter': 4, 'extras': 0, 'total': 4}
S Dhawan faced STR Binny → {'batter': 0, 'extras': 0, 'total': 0}
MC Henriques faced STR Binny → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced STR Binny → {'batter': 2, 'extras': 0, 'total': 2}
Yuvraj Singh faced STR Binny → {'batter': 2, 'extras': 0, 'total': 2}
MC Henriques faced S Aravind → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced S Aravind → {'batter': 0, 'extras': 0, 'total': 0}
Yuvraj Singh faced S Aravind → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced S Aravind → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced S Aravind → {'batter': 4, 'extras': 0, 'total': 4}
Yuvraj Singh faced S Aravind → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced A Choudhary → {'batter': 4, 'extras': 0, 'total': 4}
Yuvraj Singh faced A Choudhary → {'batter': 6, 'extras': 0, 'total': 6}
Yuvraj Singh faced A Choudhary → {'batter': 4, 'extras': 0, 'total': 4}
Yuvraj Singh faced A Choudhary → {'batter': 0, 'extras': 0, 'total': 0}
Yuvraj Singh faced A Choudhary → {'batter': 0, 'extras': 1, 'total': 1}
Yuvraj Singh faced A Choudhary → {'batter': 2, 'extras': 0, 'total': 2}
Yuvraj Singh faced A Choudhary → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced SR Watson → {'batter': 4, 'extras': 0, 'total': 4}
Yuvraj Singh faced SR Watson → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced SR Watson → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced SR Watson → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced SR Watson → {'batter': 0, 'extras': 0, 'total': 0}
MC Henriques faced SR Watson → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced S Aravind → {'batter': 4, 'extras': 0, 'total': 4}
MC Henriques faced S Aravind → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced S Aravind → {'batter': 6, 'extras': 0, 'total': 6}
Yuvraj Singh faced S Aravind → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced S Aravind → {'batter': 6, 'extras': 0, 'total': 6}
MC Henriques faced S Aravind → {'batter': 1, 'extras': 0, 'total': 1}
MC Henriques faced YS Chahal → {'batter': 0, 'extras': 0, 'total': 0}
MC Henriques faced YS Chahal → {'batter': 0, 'extras': 0, 'total': 0}
Yuvraj Singh faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
DJ Hooda faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
DJ Hooda faced YS Chahal → {'batter': 1, 'extras': 0, 'total': 1}
DJ Hooda faced TS Mills → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced TS Mills → {'batter': 0, 'extras': 0, 'total': 0}
Yuvraj Singh faced TS Mills → {'batter': 4, 'extras': 0, 'total': 4}
Yuvraj Singh faced TS Mills → {'batter': 1, 'extras': 0, 'total': 1}
DJ Hooda faced TS Mills → {'batter': 0, 'extras': 0, 'total': 0}
DJ Hooda faced TS Mills → {'batter': 1, 'extras': 0, 'total': 1}
DJ Hooda faced A Choudhary → {'batter': 6, 'extras': 0, 'total': 6}
DJ Hooda faced A Choudhary → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced A Choudhary → {'batter': 0, 'extras': 1, 'total': 1}
Yuvraj Singh faced A Choudhary → {'batter': 0, 'extras': 1, 'total': 1}
Yuvraj Singh faced A Choudhary → {'batter': 4, 'extras': 0, 'total': 4}
Yuvraj Singh faced A Choudhary → {'batter': 1, 'extras': 0, 'total': 1}
DJ Hooda faced A Choudhary → {'batter': 2, 'extras': 0, 'total': 2}
DJ Hooda faced A Choudhary → {'batter': 1, 'extras': 0, 'total': 1}
DJ Hooda faced TS Mills → {'batter': 1, 'extras': 0, 'total': 1}
Yuvraj Singh faced TS Mills → {'batter': 4, 'extras': 0, 'total': 4}
Yuvraj Singh faced TS Mills → {'batter': 6, 'extras': 0, 'total': 6}
Yuvraj Singh faced TS Mills → {'batter': 0, 'extras': 0, 'total': 0}
BCJ Cutting faced TS Mills → {'batter': 1, 'extras': 0, 'total': 1}
DJ Hooda faced TS Mills → {'batter': 0, 'extras': 0, 'total': 0}
BCJ Cutting faced SR Watson → {'batter': 1, 'extras': 0, 'total': 1}
DJ Hooda faced SR Watson → {'batter': 1, 'extras': 0, 'total': 1}
BCJ Cutting faced SR Watson → {'batter': 6, 'extras': 0, 'total': 6}
BCJ Cutting faced SR Watson → {'batter': 2, 'extras': 0, 'total': 2}
BCJ Cutting faced SR Watson → {'batter': 0, 'extras': 0, 'total': 0}
BCJ Cutting faced SR Watson → {'batter': 6, 'extras': 0, 'total': 6}

In [42]:
from collections import defaultdict

def calculate_player_stats(innings):

    player_stats = defaultdict(lambda: {
        "runs": 0,
        "balls_faced": 0,
        "fours": 0,
        "sixes": 0,
        "runs_conceded": 0,
        "balls_bowled": 0,
        "wickets": 0,
        "dismissals": 0
    })

    for over in innings["overs"]:
        for delivery in over["deliveries"]:

            batter = delivery["batter"]
            bowler = delivery["bowler"]

            runs = delivery["runs"]

            player_stats[batter]["runs"] += runs["batter"]

In [43]:
stats = calculate_player_stats(match["innings"][0])

print(stats["DA Warner"])

TypeError: 'NoneType' object is not subscriptable

In [44]:
from collections import defaultdict

def calculate_player_stats(innings):

    player_stats = defaultdict(lambda: {
        "runs": 0,
        "balls_faced": 0,
        "fours": 0,
        "sixes": 0,
        "runs_conceded": 0,
        "balls_bowled": 0,
        "wickets": 0,
        "dismissals": 0
    })

    for over in innings["overs"]:
        for delivery in over["deliveries"]:

            batter = delivery["batter"]
            bowler = delivery["bowler"]

            runs = delivery["runs"]

            player_stats[batter]["runs"] += runs["batter"]

    return player_stats

In [45]:
stats = calculate_player_stats(match["innings"][0])

print(stats["DA Warner"])

{'runs': 14, 'balls_faced': 0, 'fours': 0, 'sixes': 0, 'runs_conceded': 0, 'balls_bowled': 0, 'wickets': 0, 'dismissals': 0}

In [46]:
from collections import defaultdict

def calculate_player_stats(innings):

    player_stats = defaultdict(lambda: {
        "runs": 0,
        "balls_faced": 0,
        "fours": 0,
        "sixes": 0,
        "runs_conceded": 0,
        "balls_bowled": 0,
        "wickets": 0,
        "dismissals": 0
    })

    for over in innings["overs"]:
        for delivery in over["deliveries"]:

            batter = delivery["batter"]
            bowler = delivery["bowler"]

            runs = delivery["runs"]

            # -------------------------
            # BATTING
            # -------------------------

            # Add batter's runs
            player_stats[batter]["runs"] += runs["batter"]

            # Count legal balls faced
            if "extras" not in delivery or (
                "wides" not in delivery["extras"]
                and "noballs" not in delivery["extras"]
            ):
                player_stats[batter]["balls_faced"] += 1

    return player_stats

In [47]:
stats = calculate_player_stats(match["innings"][0])

print(stats["DA Warner"])

{'runs': 14, 'balls_faced': 7, 'fours': 0, 'sixes': 0, 'runs_conceded': 0, 'balls_bowled': 0, 'wickets': 0, 'dismissals': 0}

In [48]:
from collections import defaultdict

def calculate_player_stats(innings):

    player_stats = defaultdict(lambda: {
        "runs": 0,
        "balls_faced": 0,
        "fours": 0,
        "sixes": 0,
        "runs_conceded": 0,
        "balls_bowled": 0,
        "wickets": 0,
        "dismissals": 0
    })

    for over in innings["overs"]:
        for delivery in over["deliveries"]:

            batter = delivery["batter"]
            bowler = delivery["bowler"]

            runs = delivery["runs"]

            # -------------------------
            # BATTING
            # -------------------------

            # Add batter's runs
            player_stats[batter]["runs"] += runs["batter"]

            # Count legal balls faced
            if "extras" not in delivery or (
                "wides" not in delivery["extras"]
                and "noballs" not in delivery["extras"]
            ):
                player_stats[batter]["balls_faced"] += 1

            # Count fours
            if runs["batter"] == 4:
                player_stats[batter]["fours"] += 1

            # Count sixes
            if runs["batter"] == 6:
                player_stats[batter]["sixes"] += 1

    return player_stats

In [49]:
stats = calculate_player_stats(match["innings"][0])

print(stats["DA Warner"])

{'runs': 14, 'balls_faced': 7, 'fours': 2, 'sixes': 1, 'runs_conceded': 0, 'balls_bowled': 0, 'wickets': 0, 'dismissals': 0}

In [50]:
from collections import defaultdict

def calculate_player_stats(innings):

    player_stats = defaultdict(lambda: {
        "runs": 0,
        "balls_faced": 0,
        "fours": 0,
        "sixes": 0,
        "runs_conceded": 0,
        "balls_bowled": 0,
        "wickets": 0,
        "dismissals": 0
    })

    for over in innings["overs"]:
        for delivery in over["deliveries"]:

            batter = delivery["batter"]
            bowler = delivery["bowler"]

            runs = delivery["runs"]

            # -------------------------
            # BATTING
            # -------------------------

            # Batter runs
            player_stats[batter]["runs"] += runs["batter"]

            # Legal ball faced
            if "extras" not in delivery or (
                "wides" not in delivery["extras"]
                and "noballs" not in delivery["extras"]
            ):
                player_stats[batter]["balls_faced"] += 1

            # Fours
            if runs["batter"] == 4:
                player_stats[batter]["fours"] += 1

            # Sixes
            if runs["batter"] == 6:
                player_stats[batter]["sixes"] += 1

            # -------------------------
            # BOWLING
            # -------------------------

            # Legal ball bowled
            if "extras" not in delivery or (
                "wides" not in delivery["extras"]
                and "noballs" not in delivery["extras"]
            ):
                player_stats[bowler]["balls_bowled"] += 1

    return player_stats

In [51]:
stats = calculate_player_stats(match["innings"][0])

print(stats["TS Mills"])

{'runs': 0, 'balls_faced': 0, 'fours': 0, 'sixes': 0, 'runs_conceded': 0, 'balls_bowled': 24, 'wickets': 0, 'dismissals': 0}

In [52]:
from collections import defaultdict

def calculate_player_stats(innings):

    player_stats = defaultdict(lambda: {
        "runs": 0,
        "balls_faced": 0,
        "fours": 0,
        "sixes": 0,
        "runs_conceded": 0,
        "balls_bowled": 0,
        "wickets": 0,
        "dismissals": 0
    })

    for over in innings["overs"]:
        for delivery in over["deliveries"]:

            batter = delivery["batter"]
            bowler = delivery["bowler"]

            runs = delivery["runs"]

            # -------------------------
            # BATTING
            # -------------------------

            # Batter runs
            player_stats[batter]["runs"] += runs["batter"]

            # Legal ball faced
            if "extras" not in delivery or (
                "wides" not in delivery["extras"]
                and "noballs" not in delivery["extras"]
            ):
                player_stats[batter]["balls_faced"] += 1

            # Fours
            if runs["batter"] == 4:
                player_stats[batter]["fours"] += 1

            # Sixes
            if runs["batter"] == 6:
                player_stats[batter]["sixes"] += 1

            # -------------------------
            # BOWLING
            # -------------------------

            # Legal ball bowled
            if "extras" not in delivery or (
                "wides" not in delivery["extras"]
                and "noballs" not in delivery["extras"]
            ):
                player_stats[bowler]["balls_bowled"] += 1

            # Runs conceded by bowler
            bowler_runs = runs["total"]

            if "extras" in delivery:
                if "byes" in delivery["extras"]:
                    bowler_runs -= delivery["extras"]["byes"]

                if "legbyes" in delivery["extras"]:
                    bowler_runs -= delivery["extras"]["legbyes"]

            player_stats[bowler]["runs_conceded"] += bowler_runs

    return player_stats

In [53]:
stats = calculate_player_stats(match["innings"][0])

print(stats["TS Mills"])

{'runs': 0, 'balls_faced': 0, 'fours': 0, 'sixes': 0, 'runs_conceded': 31, 'balls_bowled': 24, 'wickets': 0, 'dismissals': 0}

In [54]:
for over in innings["overs"]:
    for delivery in over["deliveries"]:

        if delivery["bowler"] == "TS Mills":
            print(
                delivery["actual_delivery"],
                delivery["batter"],
                delivery["runs"],
                delivery.get("extras", {})
            )

0.1 DA Warner {'batter': 0, 'extras': 0, 'total': 0} {}
0.2 DA Warner {'batter': 0, 'extras': 0, 'total': 0} {}
0.3 DA Warner {'batter': 4, 'extras': 0, 'total': 4} {}
0.4 DA Warner {'batter': 0, 'extras': 0, 'total': 0} {}
0.5 DA Warner {'batter': 0, 'extras': 2, 'total': 2} {'wides': 2}
0.5 S Dhawan {'batter': 0, 'extras': 0, 'total': 0} {}
0.6 S Dhawan {'batter': 0, 'extras': 1, 'total': 1} {'legbyes': 1}
2.1 S Dhawan {'batter': 1, 'extras': 0, 'total': 1} {}
2.2 MC Henriques {'batter': 0, 'extras': 0, 'total': 0} {}
2.3 MC Henriques {'batter': 0, 'extras': 0, 'total': 0} {}
2.4 MC Henriques {'batter': 3, 'extras': 0, 'total': 3} {}
2.5 S Dhawan {'batter': 1, 'extras': 0, 'total': 1} {}
2.6 MC Henriques {'batter': 1, 'extras': 0, 'total': 1} {}
16.1 DJ Hooda {'batter': 1, 'extras': 0, 'total': 1} {}
16.2 Yuvraj Singh {'batter': 0, 'extras': 0, 'total': 0} {}
16.3 Yuvraj Singh {'batter': 4, 'extras': 0, 'total': 4} {}
16.4 Yuvraj Singh {'batter': 1, 'extras': 0, 'total': 1} {}
16.5 DJ Hooda {'batter': 0, 'extras': 0, 'total': 0} {}
16.6 DJ Hooda {'batter': 1, 'extras': 0, 'total': 1} {}
18.1 DJ Hooda {'batter': 1, 'extras': 0, 'total': 1} {}
18.2 Yuvraj Singh {'batter': 4, 'extras': 0, 'total': 4} {}
18.3 Yuvraj Singh {'batter': 6, 'extras': 0, 'total': 6} {}
18.4 Yuvraj Singh {'batter': 0, 'extras': 0, 'total': 0} {}
18.5 BCJ Cutting {'batter': 1, 'extras': 0, 'total': 1} {}
18.6 DJ Hooda {'batter': 0, 'extras': 0, 'total': 0} {}

In [55]:
total = 0

for over in innings["overs"]:
    for delivery in over["deliveries"]:

        if delivery["bowler"] == "TS Mills":

            runs = delivery["runs"]["total"]

            if "extras" in delivery:
                runs -= delivery["extras"].get("byes", 0)
                runs -= delivery["extras"].get("legbyes", 0)

            total += runs

print("TS Mills runs conceded:", total)

TS Mills runs conceded: 31

In [56]:
from collections import defaultdict

def calculate_player_stats(innings):

    player_stats = defaultdict(lambda: {
        "runs": 0,
        "balls_faced": 0,
        "fours": 0,
        "sixes": 0,
        "runs_conceded": 0,
        "balls_bowled": 0,
        "wickets": 0,
        "dismissals": 0
    })

    for over in innings["overs"]:
        for delivery in over["deliveries"]:

            batter = delivery["batter"]
            bowler = delivery["bowler"]
            runs = delivery["runs"]

            # -------------------------
            # BATTING
            # -------------------------

            # Batter runs
            player_stats[batter]["runs"] += runs["batter"]

            # Legal ball faced
            if "extras" not in delivery or (
                "wides" not in delivery["extras"]
                and "noballs" not in delivery["extras"]
            ):
                player_stats[batter]["balls_faced"] += 1

            # Fours
            if runs["batter"] == 4:
                player_stats[batter]["fours"] += 1

            # Sixes
            if runs["batter"] == 6:
                player_stats[batter]["sixes"] += 1

            # -------------------------
            # BOWLING
            # -------------------------

            # Legal ball bowled
            if "extras" not in delivery or (
                "wides" not in delivery["extras"]
                and "noballs" not in delivery["extras"]
            ):
                player_stats[bowler]["balls_bowled"] += 1

            # Runs conceded by bowler
            bowler_runs = runs["total"]

            if "extras" in delivery:
                bowler_runs -= delivery["extras"].get("byes", 0)
                bowler_runs -= delivery["extras"].get("legbyes", 0)

            player_stats[bowler]["runs_conceded"] += bowler_runs

            # -------------------------
            # WICKETS
            # -------------------------

            if "wickets" in delivery:

                for wicket in delivery["wickets"]:

                    player_out = wicket["player_out"]
                    wicket_kind = wicket["kind"]

                    # Batter was dismissed
                    player_stats[player_out]["dismissals"] += 1

                    # Bowler gets credit for these wickets
                    if wicket_kind not in [
                        "run out",
                        "retired hurt",
                        "retired out",
                        "obstructing the field"
                    ]:
                        player_stats[bowler]["wickets"] += 1

    return player_stats

In [57]:
stats = calculate_player_stats(match["innings"][0])

print(stats["TS Mills"])
print(stats["A Choudhary"])
print(stats["DA Warner"])

{'runs': 0, 'balls_faced': 0, 'fours': 0, 'sixes': 0, 'runs_conceded': 31, 'balls_bowled': 24, 'wickets': 1, 'dismissals': 0}
{'runs': 0, 'balls_faced': 0, 'fours': 0, 'sixes': 0, 'runs_conceded': 55, 'balls_bowled': 24, 'wickets': 1, 'dismissals': 0}
{'runs': 14, 'balls_faced': 7, 'fours': 2, 'sixes': 1, 'runs_conceded': 0, 'balls_bowled': 0, 'wickets': 0, 'dismissals': 1}